// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOvVdQ11TbUTu0ZPhflwyg0PXi9VrSn2g',
    appId: '1:635132466395:web:8a3ffc9bcb8f3c340328fe',
    messagingSenderId: '635132466395',
    projectId: 'steel-sequencer-385510',
    authDomain: 'steel-sequencer-385510.firebaseapp.com',
    storageBucket: 'steel-sequencer-385510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvgMgA4ePEsC8t6iGuvTzOK2pic0Z-ags',
    appId: '1:635132466395:android:6d41688a2da6b5830328fe',
    messagingSenderId: '635132466395',
    projectId: 'steel-sequencer-385510',
    storageBucket: 'steel-sequencer-385510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFoO7egCmEI9D7_lAlw1SvOKG1ZpTNOU',
    appId: '1:635132466395:ios:d3d2ab57f6b9d23b0328fe',
    messagingSenderId: '635132466395',
    projectId: 'steel-sequencer-385510',
    storageBucket: 'steel-sequencer-385510.appspot.com',
    iosClientId: '635132466395-3jnltce0jptki6atar5epb970lbrr6qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOFoO7egCmEI9D7_lAlw1SvOKG1ZpTNOU',
    appId: '1:635132466395:ios:d3d2ab57f6b9d23b0328fe',
    messagingSenderId: '635132466395',
    projectId: 'steel-sequencer-385510',
    storageBucket: 'steel-sequencer-385510.appspot.com',
    iosClientId: '635132466395-3jnltce0jptki6atar5epb970lbrr6qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasic',
  );
}
